// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatEnum.proto

#include "ChatEnum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace Chat {
}  // namespace Chat
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_ChatEnum_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_ChatEnum_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_ChatEnum_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_ChatEnum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016ChatEnum.proto\022\004Chat*\247\001\n\013MessageCode\022\021"
  "\n\rPKT_REQ_LOGIN\020\000\022\021\n\rPKT_RES_LOGIN\020\001\022\020\n\014"
  "PKT_REQ_LIST\020\002\022\020\n\014PKT_RES_LIST\020\003\022\020\n\014PKT_"
  "REQ_CHAT\020\004\022\020\n\014PKT_RES_CHAT\020\005\022\024\n\020PKT_REQ_"
  "CHATNOTI\020\006\022\024\n\020PKT_RES_CHATNOTI\020\007b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_ChatEnum_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ChatEnum_2eproto = {
  false, false, 200, descriptor_table_protodef_ChatEnum_2eproto, "ChatEnum.proto", 
  &descriptor_table_ChatEnum_2eproto_once, nullptr, 0, 0,
  schemas, file_default_instances, TableStruct_ChatEnum_2eproto::offsets,
  nullptr, file_level_enum_descriptors_ChatEnum_2eproto, file_level_service_descriptors_ChatEnum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_ChatEnum_2eproto_getter() {
  return &descriptor_table_ChatEnum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_ChatEnum_2eproto(&descriptor_table_ChatEnum_2eproto);
namespace Chat {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ChatEnum_2eproto);
  return file_level_enum_descriptors_ChatEnum_2eproto[0];
}
bool MessageCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Chat
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
