// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameProtocol.proto

#include "GameProtocol.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace Game {
constexpr REQ_CHARACTER_LIST::REQ_CHARACTER_LIST(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : token_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , id_(uint64_t{0u}){}
struct REQ_CHARACTER_LISTDefaultTypeInternal {
  constexpr REQ_CHARACTER_LISTDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~REQ_CHARACTER_LISTDefaultTypeInternal() {}
  union {
    REQ_CHARACTER_LIST _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT REQ_CHARACTER_LISTDefaultTypeInternal _REQ_CHARACTER_LIST_default_instance_;
constexpr RES_CHARACTER_LIST::RES_CHARACTER_LIST(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : characters_(){}
struct RES_CHARACTER_LISTDefaultTypeInternal {
  constexpr RES_CHARACTER_LISTDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~RES_CHARACTER_LISTDefaultTypeInternal() {}
  union {
    RES_CHARACTER_LIST _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT RES_CHARACTER_LISTDefaultTypeInternal _RES_CHARACTER_LIST_default_instance_;
}  // namespace Game
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_GameProtocol_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_GameProtocol_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_GameProtocol_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_GameProtocol_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Game::REQ_CHARACTER_LIST, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Game::REQ_CHARACTER_LIST, id_),
  PROTOBUF_FIELD_OFFSET(::Game::REQ_CHARACTER_LIST, token_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Game::RES_CHARACTER_LIST, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Game::RES_CHARACTER_LIST, characters_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Game::REQ_CHARACTER_LIST)},
  { 7, -1, sizeof(::Game::RES_CHARACTER_LIST)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Game::_REQ_CHARACTER_LIST_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Game::_RES_CHARACTER_LIST_default_instance_),
};

const char descriptor_table_protodef_GameProtocol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022GameProtocol.proto\022\004Game\032\016GameEnum.pro"
  "to\032\020GameStruct.proto\"/\n\022REQ_CHARACTER_LI"
  "ST\022\n\n\002id\030\001 \001(\004\022\r\n\005token\030\002 \001(\t\"B\n\022RES_CHA"
  "RACTER_LIST\022,\n\nCharacters\030\001 \003(\0132\030.Game.L"
  "obbyCharacterInfob\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_GameProtocol_2eproto_deps[2] = {
  &::descriptor_table_GameEnum_2eproto,
  &::descriptor_table_GameStruct_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_GameProtocol_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_GameProtocol_2eproto = {
  false, false, 185, descriptor_table_protodef_GameProtocol_2eproto, "GameProtocol.proto", 
  &descriptor_table_GameProtocol_2eproto_once, descriptor_table_GameProtocol_2eproto_deps, 2, 2,
  schemas, file_default_instances, TableStruct_GameProtocol_2eproto::offsets,
  file_level_metadata_GameProtocol_2eproto, file_level_enum_descriptors_GameProtocol_2eproto, file_level_service_descriptors_GameProtocol_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_GameProtocol_2eproto_getter() {
  return &descriptor_table_GameProtocol_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_GameProtocol_2eproto(&descriptor_table_GameProtocol_2eproto);
namespace Game {

// ===================================================================

class REQ_CHARACTER_LIST::_Internal {
 public:
};

REQ_CHARACTER_LIST::REQ_CHARACTER_LIST(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Game.REQ_CHARACTER_LIST)
}
REQ_CHARACTER_LIST::REQ_CHARACTER_LIST(const REQ_CHARACTER_LIST& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  token_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_token().empty()) {
    token_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_token(), 
      GetArenaForAllocation());
  }
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:Game.REQ_CHARACTER_LIST)
}

void REQ_CHARACTER_LIST::SharedCtor() {
token_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
id_ = uint64_t{0u};
}

REQ_CHARACTER_LIST::~REQ_CHARACTER_LIST() {
  // @@protoc_insertion_point(destructor:Game.REQ_CHARACTER_LIST)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void REQ_CHARACTER_LIST::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  token_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void REQ_CHARACTER_LIST::ArenaDtor(void* object) {
  REQ_CHARACTER_LIST* _this = reinterpret_cast< REQ_CHARACTER_LIST* >(object);
  (void)_this;
}
void REQ_CHARACTER_LIST::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void REQ_CHARACTER_LIST::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void REQ_CHARACTER_LIST::Clear() {
// @@protoc_insertion_point(message_clear_start:Game.REQ_CHARACTER_LIST)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  token_.ClearToEmpty();
  id_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* REQ_CHARACTER_LIST::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string token = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_token();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Game.REQ_CHARACTER_LIST.token"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* REQ_CHARACTER_LIST::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Game.REQ_CHARACTER_LIST)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 id = 1;
  if (this->id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_id(), target);
  }

  // string token = 2;
  if (!this->token().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_token().data(), static_cast<int>(this->_internal_token().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Game.REQ_CHARACTER_LIST.token");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_token(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Game.REQ_CHARACTER_LIST)
  return target;
}

size_t REQ_CHARACTER_LIST::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Game.REQ_CHARACTER_LIST)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string token = 2;
  if (!this->token().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_token());
  }

  // uint64 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void REQ_CHARACTER_LIST::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Game.REQ_CHARACTER_LIST)
  GOOGLE_DCHECK_NE(&from, this);
  const REQ_CHARACTER_LIST* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<REQ_CHARACTER_LIST>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Game.REQ_CHARACTER_LIST)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Game.REQ_CHARACTER_LIST)
    MergeFrom(*source);
  }
}

void REQ_CHARACTER_LIST::MergeFrom(const REQ_CHARACTER_LIST& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Game.REQ_CHARACTER_LIST)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from.token().empty()) {
    _internal_set_token(from._internal_token());
  }
  if (from.id() != 0) {
    _internal_set_id(from._internal_id());
  }
}

void REQ_CHARACTER_LIST::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Game.REQ_CHARACTER_LIST)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void REQ_CHARACTER_LIST::CopyFrom(const REQ_CHARACTER_LIST& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Game.REQ_CHARACTER_LIST)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool REQ_CHARACTER_LIST::IsInitialized() const {
  return true;
}

void REQ_CHARACTER_LIST::InternalSwap(REQ_CHARACTER_LIST* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &token_, GetArenaForAllocation(),
      &other->token_, other->GetArenaForAllocation()
  );
  swap(id_, other->id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata REQ_CHARACTER_LIST::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_GameProtocol_2eproto_getter, &descriptor_table_GameProtocol_2eproto_once,
      file_level_metadata_GameProtocol_2eproto[0]);
}

// ===================================================================

class RES_CHARACTER_LIST::_Internal {
 public:
};

void RES_CHARACTER_LIST::clear_characters() {
  characters_.Clear();
}
RES_CHARACTER_LIST::RES_CHARACTER_LIST(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  characters_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Game.RES_CHARACTER_LIST)
}
RES_CHARACTER_LIST::RES_CHARACTER_LIST(const RES_CHARACTER_LIST& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      characters_(from.characters_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Game.RES_CHARACTER_LIST)
}

void RES_CHARACTER_LIST::SharedCtor() {
}

RES_CHARACTER_LIST::~RES_CHARACTER_LIST() {
  // @@protoc_insertion_point(destructor:Game.RES_CHARACTER_LIST)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RES_CHARACTER_LIST::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void RES_CHARACTER_LIST::ArenaDtor(void* object) {
  RES_CHARACTER_LIST* _this = reinterpret_cast< RES_CHARACTER_LIST* >(object);
  (void)_this;
}
void RES_CHARACTER_LIST::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RES_CHARACTER_LIST::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void RES_CHARACTER_LIST::Clear() {
// @@protoc_insertion_point(message_clear_start:Game.RES_CHARACTER_LIST)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  characters_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RES_CHARACTER_LIST::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .Game.LobbyCharacterInfo Characters = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_characters(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RES_CHARACTER_LIST::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Game.RES_CHARACTER_LIST)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Game.LobbyCharacterInfo Characters = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_characters_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_characters(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Game.RES_CHARACTER_LIST)
  return target;
}

size_t RES_CHARACTER_LIST::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Game.RES_CHARACTER_LIST)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Game.LobbyCharacterInfo Characters = 1;
  total_size += 1UL * this->_internal_characters_size();
  for (const auto& msg : this->characters_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RES_CHARACTER_LIST::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Game.RES_CHARACTER_LIST)
  GOOGLE_DCHECK_NE(&from, this);
  const RES_CHARACTER_LIST* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RES_CHARACTER_LIST>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Game.RES_CHARACTER_LIST)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Game.RES_CHARACTER_LIST)
    MergeFrom(*source);
  }
}

void RES_CHARACTER_LIST::MergeFrom(const RES_CHARACTER_LIST& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Game.RES_CHARACTER_LIST)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  characters_.MergeFrom(from.characters_);
}

void RES_CHARACTER_LIST::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Game.RES_CHARACTER_LIST)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RES_CHARACTER_LIST::CopyFrom(const RES_CHARACTER_LIST& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Game.RES_CHARACTER_LIST)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RES_CHARACTER_LIST::IsInitialized() const {
  return true;
}

void RES_CHARACTER_LIST::InternalSwap(RES_CHARACTER_LIST* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  characters_.InternalSwap(&other->characters_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RES_CHARACTER_LIST::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_GameProtocol_2eproto_getter, &descriptor_table_GameProtocol_2eproto_once,
      file_level_metadata_GameProtocol_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Game
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Game::REQ_CHARACTER_LIST* Arena::CreateMaybeMessage< ::Game::REQ_CHARACTER_LIST >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Game::REQ_CHARACTER_LIST >(arena);
}
template<> PROTOBUF_NOINLINE ::Game::RES_CHARACTER_LIST* Arena::CreateMaybeMessage< ::Game::RES_CHARACTER_LIST >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Game::RES_CHARACTER_LIST >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
